CE103 Algorithms and Programming I HW4: DLL.FileOperations Class Reference
DLL.FileOperations Class Reference
Static Public Member Functions
static void writeLine (String line, String path, int lineLength) throws IOException
static byte[] readBlock (int count, int blocksize, String path) throws IOException
static boolean appendBlock (byte[] data, String path) throws IOException
static boolean updateBlock (byte[] data, int offset, int blocksize, String path) throws IOException
static boolean deleteBlock2 (int blockSize, int offset, String path)
static boolean deleteBlock (int count, int blocksize, String path) throws IOException
Member Function Documentation
appendBlock()
static boolean DLL.FileOperations.appendBlock (byte[] data, String path) throws IOException static
Referenced by DLL.MainFunctions.AddBill(), DLL.MainFunctions.AddCustomer(), DLL.MainFunctions.AddMedicine(), DLL.MainFunctions.AddSaleMedicine(), DLL.MainFunctions.AddSupplier(), DLL.UnitTest.testSupplierCreation(), and DLL.UnitTest.testSupplierCreationAndFileWriting().
deleteBlock()
static boolean DLL.FileOperations.deleteBlock (int count, int blocksize, String path) throws IOException static
deleteBlock2()
static boolean DLL.FileOperations.deleteBlock2 (int blockSize, int offset, String path) static
References DLL.DataOperations.StringToByteArray().
Referenced by APP.MainMenu.option1(), APP.MainMenu.option2(), and APP.MainMenu.option3().
readBlock()
static byte[] DLL.FileOperations.readBlock (int count, int blocksize, String path) throws IOException static
Referenced by APP.MainMenu.option1(), APP.MainMenu.option2(), APP.MainMenu.option3(), APP.MainMenu.option4(), APP.MainMenu.option5(), and DLL.UnitTest.testReadBlock().
updateBlock()
static boolean DLL.FileOperations.updateBlock (byte[] data, int offset, int blocksize, String path) throws IOException static
Referenced by APP.MainMenu.option1(), APP.MainMenu.option2(), APP.MainMenu.option3(), and DLL.UnitTest.testUpdateBlock().
writeLine()
static void DLL.FileOperations.writeLine (String line, String path, int lineLength) throws IOException static
Referenced by DLL.UnitTest.testWriteLine().
The documentation for this class was generated from the following file:
C:/HW/CE-103-2022-2023-HW4-Eray-Burak-Cakir/ce103-hw4-medicalstore-lib/src/DLL/FileOperations.java