CE103 Algorithms and Programming I HW4: DLL.SupplierFeature Class Reference
DLL.SupplierFeature Class Reference
Public Member Functions
final int getId ()
final void setId (int value)
final long getContactNum ()
final void setContactNum (long value)
final String getSupplierName ()
final void setSupplierName (String value)
final String getCityName ()
final void setCityName (String value)
final String getEmail ()
final void setEmail (String value)
Static Public Member Functions
static byte[] BookToByteArrayBlock (SupplierFeature supplier)
static SupplierFeature ByteArrayBlockToBook (byte[] byteArray)
Static Public Attributes
static final int ID_LENGTH = 4
static final int SUPPLIER_NAME_MAX_LENGTH = 50
static final int CITY_NAME_MAX_LENGTH = 50
static final int CONTACT_NUMBER_MAX_LENGTH = 20
static final int EMAİL_MAX_LENGTH = 50
static final int SUPPLIER_DATA_BLOCK_SIZE = ID_LENGTH + SUPPLIER_NAME_MAX_LENGTH + CITY_NAME_MAX_LENGTH + CONTACT_NUMBER_MAX_LENGTH + EMAİL_MAX_LENGTH
Private Attributes
int _id
long _contactNum
String _supplierName
String _cityName
String _email
Member Function Documentation
BookToByteArrayBlock()
static byte[] DLL.SupplierFeature.BookToByteArrayBlock (SupplierFeature supplier) static
References DLL.SupplierFeature.CITY_NAME_MAX_LENGTH, DLL.SupplierFeature.CONTACT_NUMBER_MAX_LENGTH, DLL.DataOperations.convertLongToByteArray(), DLL.SupplierFeature.EMAİL_MAX_LENGTH, DLL.SupplierFeature.getCityName(), DLL.SupplierFeature.getContactNum(), DLL.SupplierFeature.getEmail(), DLL.SupplierFeature.getId(), DLL.SupplierFeature.getSupplierName(), DLL.SupplierFeature.ID_LENGTH, DLL.DataOperations.integerToByteArray(), DLL.DataOperations.StringToByteArray(), DLL.SupplierFeature.SUPPLIER_DATA_BLOCK_SIZE, and DLL.SupplierFeature.SUPPLIER_NAME_MAX_LENGTH.
Referenced by DLL.MainFunctions.AddSupplier(), APP.MainMenu.option1(), DLL.UnitTest.testSupplierCreation(), and DLL.UnitTest.testSupplierCreationAndFileWriting().
ByteArrayBlockToBook()
static SupplierFeature DLL.SupplierFeature.ByteArrayBlockToBook (byte[] byteArray) static
References DLL.DataOperations.byteArrayToInteger(), DLL.DataOperations.byteArrayToLong(), DLL.DataOperations.byteArrayToString(), DLL.SupplierFeature.CITY_NAME_MAX_LENGTH, DLL.SupplierFeature.CONTACT_NUMBER_MAX_LENGTH, DLL.SupplierFeature.EMAİL_MAX_LENGTH, DLL.SupplierFeature.getId(), DLL.SupplierFeature.ID_LENGTH, DLL.SupplierFeature.setCityName(), DLL.SupplierFeature.setContactNum(), DLL.SupplierFeature.setEmail(), DLL.SupplierFeature.setId(), DLL.SupplierFeature.setSupplierName(), DLL.SupplierFeature.SUPPLIER_DATA_BLOCK_SIZE, and DLL.SupplierFeature.SUPPLIER_NAME_MAX_LENGTH.
Referenced by APP.MainMenu.option1().
getCityName()
final String DLL.SupplierFeature.getCityName ()
References DLL.SupplierFeature._cityName.
Referenced by DLL.SupplierFeature.BookToByteArrayBlock(), APP.MainMenu.option1(), and DLL.UnitTest.testSupplierCreation().
getContactNum()
final long DLL.SupplierFeature.getContactNum ()
References DLL.SupplierFeature._contactNum.
Referenced by DLL.SupplierFeature.BookToByteArrayBlock(), APP.MainMenu.option1(), and DLL.UnitTest.testSupplierCreation().
getEmail()
final String DLL.SupplierFeature.getEmail ()
References DLL.SupplierFeature._email.
Referenced by DLL.SupplierFeature.BookToByteArrayBlock(), APP.MainMenu.option1(), and DLL.UnitTest.testSupplierCreation().
getId()
final int DLL.SupplierFeature.getId ()
References DLL.SupplierFeature._id.
Referenced by DLL.SupplierFeature.BookToByteArrayBlock(), DLL.SupplierFeature.ByteArrayBlockToBook(), APP.MainMenu.option1(), and DLL.UnitTest.testSupplierCreation().
getSupplierName()
final String DLL.SupplierFeature.getSupplierName ()
References DLL.SupplierFeature._supplierName.
Referenced by DLL.SupplierFeature.BookToByteArrayBlock(), APP.MainMenu.option1(), and DLL.UnitTest.testSupplierCreation().
setCityName()
final void DLL.SupplierFeature.setCityName (String value)
References DLL.SupplierFeature._cityName.
Referenced by DLL.MainFunctions.AddSupplier(), DLL.SupplierFeature.ByteArrayBlockToBook(), APP.MainMenu.option1(), DLL.UnitTest.testSupplierCreation(), and DLL.UnitTest.testSupplierCreationAndFileWriting().
setContactNum()
final void DLL.SupplierFeature.setContactNum (long value)
References DLL.SupplierFeature._contactNum.
Referenced by DLL.MainFunctions.AddSupplier(), DLL.SupplierFeature.ByteArrayBlockToBook(), APP.MainMenu.option1(), DLL.UnitTest.testSupplierCreation(), and DLL.UnitTest.testSupplierCreationAndFileWriting().
setEmail()
final void DLL.SupplierFeature.setEmail (String value)
References DLL.SupplierFeature._email.
Referenced by DLL.MainFunctions.AddSupplier(), DLL.SupplierFeature.ByteArrayBlockToBook(), APP.MainMenu.option1(), DLL.UnitTest.testSupplierCreation(), and DLL.UnitTest.testSupplierCreationAndFileWriting().
setId()
final void DLL.SupplierFeature.setId (int value)
References DLL.SupplierFeature._id.
Referenced by DLL.MainFunctions.AddSupplier(), DLL.SupplierFeature.ByteArrayBlockToBook(), APP.MainMenu.option1(), DLL.UnitTest.testSupplierCreation(), and DLL.UnitTest.testSupplierCreationAndFileWriting().
setSupplierName()
final void DLL.SupplierFeature.setSupplierName (String value)
References DLL.SupplierFeature._supplierName.
Referenced by DLL.MainFunctions.AddSupplier(), DLL.SupplierFeature.ByteArrayBlockToBook(), APP.MainMenu.option1(), DLL.UnitTest.testSupplierCreation(), and DLL.UnitTest.testSupplierCreationAndFileWriting().
Member Data Documentation
_cityName
String DLL.SupplierFeature._cityName private
Referenced by DLL.SupplierFeature.getCityName(), and DLL.SupplierFeature.setCityName().
_contactNum
long DLL.SupplierFeature._contactNum private
Referenced by DLL.SupplierFeature.getContactNum(), and DLL.SupplierFeature.setContactNum().
_email
String DLL.SupplierFeature._email private
Referenced by DLL.SupplierFeature.getEmail(), and DLL.SupplierFeature.setEmail().
_id
int DLL.SupplierFeature._id private
Referenced by DLL.SupplierFeature.getId(), and DLL.SupplierFeature.setId().
_supplierName
String DLL.SupplierFeature._supplierName private
Referenced by DLL.SupplierFeature.getSupplierName(), and DLL.SupplierFeature.setSupplierName().
CITY_NAME_MAX_LENGTH
final int DLL.SupplierFeature.CITY_NAME_MAX_LENGTH = 50 static
Referenced by DLL.SupplierFeature.BookToByteArrayBlock(), and DLL.SupplierFeature.ByteArrayBlockToBook().
CONTACT_NUMBER_MAX_LENGTH
final int DLL.SupplierFeature.CONTACT_NUMBER_MAX_LENGTH = 20 static
Referenced by DLL.SupplierFeature.BookToByteArrayBlock(), and DLL.SupplierFeature.ByteArrayBlockToBook().
EMAİL_MAX_LENGTH
final int DLL.SupplierFeature.EMAİL_MAX_LENGTH = 50 static
Referenced by DLL.SupplierFeature.BookToByteArrayBlock(), and DLL.SupplierFeature.ByteArrayBlockToBook().
ID_LENGTH
final int DLL.SupplierFeature.ID_LENGTH = 4 static
Referenced by DLL.SupplierFeature.BookToByteArrayBlock(), DLL.CustomerFeature.ByteArrayBlockToBook(), and DLL.SupplierFeature.ByteArrayBlockToBook().
SUPPLIER_DATA_BLOCK_SIZE
final int DLL.SupplierFeature.SUPPLIER_DATA_BLOCK_SIZE = ID_LENGTH + SUPPLIER_NAME_MAX_LENGTH + CITY_NAME_MAX_LENGTH + CONTACT_NUMBER_MAX_LENGTH + EMAİL_MAX_LENGTH static
Referenced by DLL.SupplierFeature.BookToByteArrayBlock(), DLL.SupplierFeature.ByteArrayBlockToBook(), and APP.MainMenu.option1().
SUPPLIER_NAME_MAX_LENGTH
final int DLL.SupplierFeature.SUPPLIER_NAME_MAX_LENGTH = 50 static
Referenced by DLL.SupplierFeature.BookToByteArrayBlock(), and DLL.SupplierFeature.ByteArrayBlockToBook().
The documentation for this class was generated from the following file:
C:/HW/CE-103-2022-2023-HW4-Eray-Burak-Cakir/ce103-hw4-medicalstore-lib/src/DLL/SupplierFeature.java