CE103 Algorithms and Programming I HW4: DLL.MainFunctions Class Reference
DLL.MainFunctions Class Reference
Static Public Member Functions
static final void AddSupplier (int Id, long ContactNumber, String SupplierName, String CityName, String Email) throws IOException
static final void AddCustomer (int Id, long ContactNumber, String CustomerName, String CityName, String Email) throws IOException
static final void AddMedicine (int Id, String MedicineName, String MedicineSupplier, String CompanyName, double Price, int Quantity, int Rack, int Cabnit) throws IOException
static final void AddBill (int BillId, int CustomerId, int MedicineId, int MedicineQuantity) throws IOException
static final void AddSaleMedicine (int MedicineId, int CustomerId, int MedicineQuantity, String SaleDate) throws IOException
static final void ControlFile (String FileName) throws IOException
Member Function Documentation
AddBill()
static final void DLL.MainFunctions.AddBill (int BillId, int CustomerId, int MedicineId, int MedicineQuantity) throws IOException static
References DLL.FileOperations.appendBlock(), DLL.BillFeature.BookToByteArrayBlock(), DLL.MainFunctions.ControlFile(), DLL.BillFeature.setCustomerId(), DLL.BillFeature.setId(), DLL.BillFeature.setMedicineId(), and DLL.BillFeature.setMedicineQuantity().
Referenced by APP.MainMenu.option5(), and DLL.UnitTest.testAddBill().
AddCustomer()
static final void DLL.MainFunctions.AddCustomer (int Id, long ContactNumber, String CustomerName, String CityName, String Email) throws IOException static
References DLL.FileOperations.appendBlock(), DLL.CustomerFeature.BookToByteArrayBlock(), DLL.MainFunctions.ControlFile(), DLL.CustomerFeature.setCityName(), DLL.CustomerFeature.setContactNum(), DLL.CustomerFeature.setCustomerName(), DLL.CustomerFeature.setEmail(), and DLL.CustomerFeature.setId().
Referenced by APP.MainMenu.option2(), and DLL.UnitTest.testAddCustomer().
AddMedicine()
static final void DLL.MainFunctions.AddMedicine (int Id, String MedicineName, String MedicineSupplier, String CompanyName, double Price, int Quantity, int Rack, int Cabnit) throws IOException static
References DLL.FileOperations.appendBlock(), DLL.MedicineFeature.BookToByteArrayBlock(), DLL.MainFunctions.ControlFile(), DLL.MedicineFeature.setCabnit(), DLL.MedicineFeature.setCompanyName(), DLL.MedicineFeature.setMedicineId(), DLL.MedicineFeature.setMedicineName(), DLL.MedicineFeature.setMedicineSupplier(), DLL.MedicineFeature.setPrice(), DLL.MedicineFeature.setQuantity(), and DLL.MedicineFeature.setRack().
Referenced by APP.MainMenu.option3(), and DLL.UnitTest.testAddMedicine().
AddSaleMedicine()
static final void DLL.MainFunctions.AddSaleMedicine (int MedicineId, int CustomerId, int MedicineQuantity, String SaleDate) throws IOException static
References DLL.FileOperations.appendBlock(), DLL.SaleMedicineFeature.BookToByteArrayBlock(), DLL.MainFunctions.ControlFile(), DLL.SaleMedicineFeature.setCustomerId(), DLL.SaleMedicineFeature.setMedicineId(), DLL.SaleMedicineFeature.setMedicineQuantity(), and DLL.SaleMedicineFeature.setSaleDate().
Referenced by APP.MainMenu.option3().
AddSupplier()
static final void DLL.MainFunctions.AddSupplier (int Id, long ContactNumber, String SupplierName, String CityName, String Email) throws IOException static
References DLL.FileOperations.appendBlock(), DLL.SupplierFeature.BookToByteArrayBlock(), DLL.MainFunctions.ControlFile(), DLL.SupplierFeature.setCityName(), DLL.SupplierFeature.setContactNum(), DLL.SupplierFeature.setEmail(), DLL.SupplierFeature.setId(), and DLL.SupplierFeature.setSupplierName().
Referenced by APP.MainMenu.option1(), and DLL.UnitTest.testAddSupplier().
ControlFile()
static final void DLL.MainFunctions.ControlFile (String FileName) throws IOException static
Referenced by DLL.MainFunctions.AddBill(), DLL.MainFunctions.AddCustomer(), DLL.MainFunctions.AddMedicine(), DLL.MainFunctions.AddSaleMedicine(), and DLL.MainFunctions.AddSupplier().
The documentation for this class was generated from the following file:
C:/HW/CE-103-2022-2023-HW4-Eray-Burak-Cakir/ce103-hw4-medicalstore-lib/src/DLL/MainFunctions.java