CE103 Algorithms and Programming I HW4: DLL.CustomerFeature Class Reference
DLL.CustomerFeature Class Reference
Public Member Functions
final int getId ()
final void setId (int value)
final long getContactNum ()
final void setContactNum (long value)
final String getCustomerName ()
final void setCustomerName (String value)
final String getCityName ()
final void setCityName (String value)
final String getEmail ()
final void setEmail (String value)
Static Public Member Functions
static byte[] BookToByteArrayBlock (CustomerFeature customer)
static CustomerFeature ByteArrayBlockToBook (byte[] byteArray)
Static Public Attributes
static final int ID_LENGTH = 4
static final int CUSTOMER_NAME_MAX_LENGTH = 50
static final int CITY_NAME_MAX_LENGTH = 50
static final int CONTACT_NUMBER_MAX_LENGTH = 15
static final int EMAİL_MAX_LENGTH = 51
static final int CUSTOMER_DATA_BLOCK_SIZE = ID_LENGTH + CUSTOMER_NAME_MAX_LENGTH + CITY_NAME_MAX_LENGTH + CONTACT_NUMBER_MAX_LENGTH + EMAİL_MAX_LENGTH
Private Attributes
int _id
long _contactNum
String _customerName
String _cityName
String _email
Member Function Documentation
BookToByteArrayBlock()
static byte[] DLL.CustomerFeature.BookToByteArrayBlock (CustomerFeature customer) static
References DLL.CustomerFeature.CITY_NAME_MAX_LENGTH, DLL.CustomerFeature.CONTACT_NUMBER_MAX_LENGTH, DLL.DataOperations.convertLongToByteArray(), DLL.CustomerFeature.CUSTOMER_DATA_BLOCK_SIZE, DLL.CustomerFeature.CUSTOMER_NAME_MAX_LENGTH, DLL.CustomerFeature.EMAİL_MAX_LENGTH, DLL.CustomerFeature.getCityName(), DLL.CustomerFeature.getContactNum(), DLL.CustomerFeature.getCustomerName(), DLL.CustomerFeature.getEmail(), DLL.CustomerFeature.getId(), DLL.CustomerFeature.ID_LENGTH, DLL.DataOperations.integerToByteArray(), and DLL.DataOperations.StringToByteArray().
Referenced by DLL.MainFunctions.AddCustomer(), APP.MainMenu.option2(), and DLL.UnitTest.testByteArrayBlockToBook().
ByteArrayBlockToBook()
static CustomerFeature DLL.CustomerFeature.ByteArrayBlockToBook (byte[] byteArray) static
References DLL.DataOperations.byteArrayToInteger(), DLL.DataOperations.byteArrayToLong(), DLL.DataOperations.byteArrayToString(), DLL.CustomerFeature.CITY_NAME_MAX_LENGTH, DLL.CustomerFeature.CONTACT_NUMBER_MAX_LENGTH, DLL.CustomerFeature.CUSTOMER_DATA_BLOCK_SIZE, DLL.CustomerFeature.CUSTOMER_NAME_MAX_LENGTH, DLL.CustomerFeature.EMAİL_MAX_LENGTH, DLL.CustomerFeature.getId(), DLL.CustomerFeature.ID_LENGTH, DLL.SupplierFeature.ID_LENGTH, DLL.CustomerFeature.setCityName(), DLL.CustomerFeature.setContactNum(), DLL.CustomerFeature.setCustomerName(), DLL.CustomerFeature.setEmail(), and DLL.CustomerFeature.setId().
Referenced by APP.MainMenu.option2(), APP.MainMenu.option3(), APP.MainMenu.option5(), and DLL.UnitTest.testByteArrayBlockToBook().
getCityName()
final String DLL.CustomerFeature.getCityName ()
References DLL.CustomerFeature._cityName.
Referenced by DLL.CustomerFeature.BookToByteArrayBlock(), APP.MainMenu.option2(), APP.MainMenu.option3(), and APP.MainMenu.option5().
getContactNum()
final long DLL.CustomerFeature.getContactNum ()
References DLL.CustomerFeature._contactNum.
Referenced by DLL.CustomerFeature.BookToByteArrayBlock(), APP.MainMenu.option2(), APP.MainMenu.option3(), and APP.MainMenu.option5().
getCustomerName()
final String DLL.CustomerFeature.getCustomerName ()
References DLL.CustomerFeature._customerName.
Referenced by DLL.CustomerFeature.BookToByteArrayBlock(), APP.MainMenu.option2(), APP.MainMenu.option3(), and APP.MainMenu.option5().
getEmail()
final String DLL.CustomerFeature.getEmail ()
References DLL.CustomerFeature._email.
Referenced by DLL.CustomerFeature.BookToByteArrayBlock(), APP.MainMenu.option2(), APP.MainMenu.option3(), and APP.MainMenu.option5().
getId()
final int DLL.CustomerFeature.getId ()
References DLL.CustomerFeature._id.
Referenced by DLL.CustomerFeature.BookToByteArrayBlock(), DLL.CustomerFeature.ByteArrayBlockToBook(), APP.MainMenu.option2(), APP.MainMenu.option3(), and APP.MainMenu.option5().
setCityName()
final void DLL.CustomerFeature.setCityName (String value)
References DLL.CustomerFeature._cityName.
Referenced by DLL.MainFunctions.AddCustomer(), DLL.CustomerFeature.ByteArrayBlockToBook(), APP.MainMenu.option2(), and DLL.UnitTest.testByteArrayBlockToBook().
setContactNum()
final void DLL.CustomerFeature.setContactNum (long value)
References DLL.CustomerFeature._contactNum.
Referenced by DLL.MainFunctions.AddCustomer(), DLL.CustomerFeature.ByteArrayBlockToBook(), APP.MainMenu.option2(), and DLL.UnitTest.testByteArrayBlockToBook().
setCustomerName()
final void DLL.CustomerFeature.setCustomerName (String value)
References DLL.CustomerFeature._customerName.
Referenced by DLL.MainFunctions.AddCustomer(), DLL.CustomerFeature.ByteArrayBlockToBook(), APP.MainMenu.option2(), and DLL.UnitTest.testByteArrayBlockToBook().
setEmail()
final void DLL.CustomerFeature.setEmail (String value)
References DLL.CustomerFeature._email.
Referenced by DLL.MainFunctions.AddCustomer(), DLL.CustomerFeature.ByteArrayBlockToBook(), APP.MainMenu.option2(), and DLL.UnitTest.testByteArrayBlockToBook().
setId()
final void DLL.CustomerFeature.setId (int value)
References DLL.CustomerFeature._id.
Referenced by DLL.MainFunctions.AddCustomer(), DLL.CustomerFeature.ByteArrayBlockToBook(), APP.MainMenu.option2(), and DLL.UnitTest.testByteArrayBlockToBook().
Member Data Documentation
_cityName
String DLL.CustomerFeature._cityName private
Referenced by DLL.CustomerFeature.getCityName(), and DLL.CustomerFeature.setCityName().
_contactNum
long DLL.CustomerFeature._contactNum private
Referenced by DLL.CustomerFeature.getContactNum(), and DLL.CustomerFeature.setContactNum().
_customerName
String DLL.CustomerFeature._customerName private
Referenced by DLL.CustomerFeature.getCustomerName(), and DLL.CustomerFeature.setCustomerName().
_email
String DLL.CustomerFeature._email private
Referenced by DLL.CustomerFeature.getEmail(), and DLL.CustomerFeature.setEmail().
_id
int DLL.CustomerFeature._id private
Referenced by DLL.CustomerFeature.getId(), and DLL.CustomerFeature.setId().
CITY_NAME_MAX_LENGTH
final int DLL.CustomerFeature.CITY_NAME_MAX_LENGTH = 50 static
Referenced by DLL.CustomerFeature.BookToByteArrayBlock(), and DLL.CustomerFeature.ByteArrayBlockToBook().
CONTACT_NUMBER_MAX_LENGTH
final int DLL.CustomerFeature.CONTACT_NUMBER_MAX_LENGTH = 15 static
Referenced by DLL.CustomerFeature.BookToByteArrayBlock(), and DLL.CustomerFeature.ByteArrayBlockToBook().
CUSTOMER_DATA_BLOCK_SIZE
final int DLL.CustomerFeature.CUSTOMER_DATA_BLOCK_SIZE = ID_LENGTH + CUSTOMER_NAME_MAX_LENGTH + CITY_NAME_MAX_LENGTH + CONTACT_NUMBER_MAX_LENGTH + EMAİL_MAX_LENGTH static
Referenced by DLL.CustomerFeature.BookToByteArrayBlock(), DLL.CustomerFeature.ByteArrayBlockToBook(), APP.MainMenu.option2(), APP.MainMenu.option3(), and APP.MainMenu.option5().
CUSTOMER_NAME_MAX_LENGTH
final int DLL.CustomerFeature.CUSTOMER_NAME_MAX_LENGTH = 50 static
Referenced by DLL.CustomerFeature.BookToByteArrayBlock(), and DLL.CustomerFeature.ByteArrayBlockToBook().
EMAİL_MAX_LENGTH
final int DLL.CustomerFeature.EMAİL_MAX_LENGTH = 51 static
Referenced by DLL.CustomerFeature.BookToByteArrayBlock(), and DLL.CustomerFeature.ByteArrayBlockToBook().
ID_LENGTH
final int DLL.CustomerFeature.ID_LENGTH = 4 static
Referenced by DLL.CustomerFeature.BookToByteArrayBlock(), and DLL.CustomerFeature.ByteArrayBlockToBook().
The documentation for this class was generated from the following file:
C:/HW/CE-103-2022-2023-HW4-Eray-Burak-Cakir/ce103-hw4-medicalstore-lib/src/DLL/CustomerFeature.java