CE103 Algorithms and Programming I HW4: DLL.UnitTest Class Reference
DLL.UnitTest Class Reference
Public Member Functions
void testSupplierCreationAndFileWriting () throws IOException
void testSupplierCreation () throws IOException
void testHexStringToByteArray ()
void testByteArrayToHexString ()
void testIsHex ()
void testGetInt ()
void testByteArrayToLong ()
void testByteArrayToInteger ()
void testByteArrayToFloat ()
void testByteArrayToString ()
void testWriteLine () throws IOException
void testReadBlock () throws IOException
void testUpdateBlock () throws IOException
void testAddSupplier () throws IOException
void testAddCustomer () throws IOException
void testByteArrayBlockToBook ()
void testAddMedicine () throws IOException
void testAddBill () throws IOException
void testAddSaleMedicine () throws IOException
Member Function Documentation
testAddBill()
void DLL.UnitTest.testAddBill () throws IOException
References DLL.MainFunctions.AddBill().
testAddCustomer()
void DLL.UnitTest.testAddCustomer () throws IOException
References DLL.MainFunctions.AddCustomer().
testAddMedicine()
void DLL.UnitTest.testAddMedicine () throws IOException
References DLL.MainFunctions.AddMedicine().
testAddSaleMedicine()
void DLL.UnitTest.testAddSaleMedicine () throws IOException
testAddSupplier()
void DLL.UnitTest.testAddSupplier () throws IOException
References DLL.MainFunctions.AddSupplier().
testByteArrayBlockToBook()
void DLL.UnitTest.testByteArrayBlockToBook ()
References DLL.CustomerFeature.BookToByteArrayBlock(), DLL.CustomerFeature.ByteArrayBlockToBook(), DLL.CustomerFeature.setCityName(), DLL.CustomerFeature.setContactNum(), DLL.CustomerFeature.setCustomerName(), DLL.CustomerFeature.setEmail(), and DLL.CustomerFeature.setId().
testByteArrayToFloat()
void DLL.UnitTest.testByteArrayToFloat ()
References DLL.DataOperations.byteArrayToFloat().
testByteArrayToHexString()
void DLL.UnitTest.testByteArrayToHexString ()
testByteArrayToInteger()
void DLL.UnitTest.testByteArrayToInteger ()
References DLL.DataOperations.byteArrayToInteger().
testByteArrayToLong()
void DLL.UnitTest.testByteArrayToLong ()
References DLL.DataOperations.byteArrayToLong().
testByteArrayToString()
void DLL.UnitTest.testByteArrayToString ()
References DLL.DataOperations.byteArrayToString().
testGetInt()
void DLL.UnitTest.testGetInt ()
References DLL.DataOperations.GetInt().
testHexStringToByteArray()
void DLL.UnitTest.testHexStringToByteArray ()
References DLL.DataOperations.ToByte().
testIsHex()
void DLL.UnitTest.testIsHex ()
References DLL.DataOperations.IsHex().
testReadBlock()
void DLL.UnitTest.testReadBlock () throws IOException
References DLL.FileOperations.readBlock().
testSupplierCreation()
void DLL.UnitTest.testSupplierCreation () throws IOException
References DLL.FileOperations.appendBlock(), DLL.SupplierFeature.BookToByteArrayBlock(), DLL.SupplierFeature.getCityName(), DLL.SupplierFeature.getContactNum(), DLL.SupplierFeature.getEmail(), DLL.SupplierFeature.getId(), DLL.SupplierFeature.getSupplierName(), DLL.SupplierFeature.setCityName(), DLL.SupplierFeature.setContactNum(), DLL.SupplierFeature.setEmail(), DLL.SupplierFeature.setId(), and DLL.SupplierFeature.setSupplierName().
testSupplierCreationAndFileWriting()
void DLL.UnitTest.testSupplierCreationAndFileWriting () throws IOException
References DLL.FileOperations.appendBlock(), DLL.SupplierFeature.BookToByteArrayBlock(), DLL.SupplierFeature.setCityName(), DLL.SupplierFeature.setContactNum(), DLL.SupplierFeature.setEmail(), DLL.SupplierFeature.setId(), and DLL.SupplierFeature.setSupplierName().
testUpdateBlock()
void DLL.UnitTest.testUpdateBlock () throws IOException
References DLL.FileOperations.updateBlock().
testWriteLine()
void DLL.UnitTest.testWriteLine () throws IOException
References DLL.FileOperations.writeLine().
The documentation for this class was generated from the following file:
C:/HW/CE-103-2022-2023-HW4-Eray-Burak-Cakir/ce103-hw4-medicalstore-lib/src/DLL/UnitTest.java