CE103 Algorithms and Programming I HW4: DLL.MedicineFeature Class Reference
DLL.MedicineFeature Class Reference
Public Member Functions
final int getMedicineId ()
final void setMedicineId (int value)
final String getMedicineName ()
final void setMedicineName (String value)
final int getQuantity ()
final void setQuantity (int value)
final double getPrice ()
final void setPrice (double value)
final int getRack ()
final void setRack (int value)
final int getCabnit ()
final void setCabnit (int value)
final String getMedicineSupplier ()
final void setMedicineSupplier (String value)
final String getCompanyName ()
final void setCompanyName (String value)
Static Public Member Functions
static byte[] BookToByteArrayBlock (MedicineFeature medicine)
static MedicineFeature ByteArrayBlockToBook (byte[] byteArray)
Static Public Attributes
static final int MEDICINE_ID_LENGTH = 4
static final int MEDICINE_NAME_MAX_LENGTH =50
static final int QUANTITY_MAX_LENGTH = 4
static final int RACK_NUMBER_MAX_LENGTH = 4
static final int CABNIT_NUMBER_MAX_LENGTH = 4
static final int MEDICINE_PRICE_LENGTH =8
static final int MEDICINE_SUPPLIER_NAME_MAX_LENGTH = 50
static final int COMPANY_NAME_MAX_LENGTH = 50
static final int MEDICINE_DATA_BLOCK_SIZE = MEDICINE_ID_LENGTH +QUANTITY_MAX_LENGTH + MEDICINE_NAME_MAX_LENGTH + MEDICINE_PRICE_LENGTH + RACK_NUMBER_MAX_LENGTH + CABNIT_NUMBER_MAX_LENGTH + MEDICINE_SUPPLIER_NAME_MAX_LENGTH + COMPANY_NAME_MAX_LENGTH
Private Attributes
int _medicineId
String _medicineName
int _quantity
int _rack
double _price
int _cabnit
String _medicineSupplier
String _companyName
Member Function Documentation
BookToByteArrayBlock()
static byte[] DLL.MedicineFeature.BookToByteArrayBlock (MedicineFeature medicine) static
References DLL.MedicineFeature.CABNIT_NUMBER_MAX_LENGTH, DLL.MedicineFeature.COMPANY_NAME_MAX_LENGTH, DLL.DataOperations.doubleToByteArray(), DLL.MedicineFeature.getCabnit(), DLL.MedicineFeature.getCompanyName(), DLL.MedicineFeature.getMedicineId(), DLL.MedicineFeature.getMedicineName(), DLL.MedicineFeature.getMedicineSupplier(), DLL.MedicineFeature.getPrice(), DLL.MedicineFeature.getQuantity(), DLL.MedicineFeature.getRack(), DLL.DataOperations.integerToByteArray(), DLL.MedicineFeature.MEDICINE_DATA_BLOCK_SIZE, DLL.MedicineFeature.MEDICINE_ID_LENGTH, DLL.MedicineFeature.MEDICINE_NAME_MAX_LENGTH, DLL.MedicineFeature.MEDICINE_PRICE_LENGTH, DLL.MedicineFeature.MEDICINE_SUPPLIER_NAME_MAX_LENGTH, DLL.MedicineFeature.QUANTITY_MAX_LENGTH, DLL.MedicineFeature.RACK_NUMBER_MAX_LENGTH, and DLL.DataOperations.StringToByteArray().
Referenced by DLL.MainFunctions.AddMedicine(), and APP.MainMenu.option3().
ByteArrayBlockToBook()
static MedicineFeature DLL.MedicineFeature.ByteArrayBlockToBook (byte[] byteArray) static
References DLL.DataOperations.byteArrayToDouble(), DLL.DataOperations.byteArrayToInteger(), DLL.DataOperations.byteArrayToString(), DLL.MedicineFeature.CABNIT_NUMBER_MAX_LENGTH, DLL.MedicineFeature.COMPANY_NAME_MAX_LENGTH, DLL.MedicineFeature.getMedicineId(), DLL.MedicineFeature.MEDICINE_DATA_BLOCK_SIZE, DLL.MedicineFeature.MEDICINE_ID_LENGTH, DLL.MedicineFeature.MEDICINE_NAME_MAX_LENGTH, DLL.MedicineFeature.MEDICINE_PRICE_LENGTH, DLL.MedicineFeature.MEDICINE_SUPPLIER_NAME_MAX_LENGTH, DLL.MedicineFeature.QUANTITY_MAX_LENGTH, DLL.MedicineFeature.RACK_NUMBER_MAX_LENGTH, DLL.MedicineFeature.setCabnit(), DLL.MedicineFeature.setCompanyName(), DLL.MedicineFeature.setMedicineId(), DLL.MedicineFeature.setMedicineName(), DLL.MedicineFeature.setMedicineSupplier(), DLL.MedicineFeature.setPrice(), DLL.MedicineFeature.setQuantity(), and DLL.MedicineFeature.setRack().
Referenced by APP.MainMenu.option3(), APP.MainMenu.option4(), and APP.MainMenu.option5().
getCabnit()
final int DLL.MedicineFeature.getCabnit ()
References DLL.MedicineFeature._cabnit.
Referenced by DLL.MedicineFeature.BookToByteArrayBlock(), and APP.MainMenu.option3().
getCompanyName()
final String DLL.MedicineFeature.getCompanyName ()
References DLL.MedicineFeature._companyName.
Referenced by DLL.MedicineFeature.BookToByteArrayBlock(), APP.MainMenu.option3(), APP.MainMenu.option4(), and APP.MainMenu.option5().
getMedicineId()
final int DLL.MedicineFeature.getMedicineId ()
References DLL.MedicineFeature._medicineId.
Referenced by DLL.MedicineFeature.BookToByteArrayBlock(), DLL.MedicineFeature.ByteArrayBlockToBook(), APP.MainMenu.option3(), APP.MainMenu.option4(), and APP.MainMenu.option5().
getMedicineName()
final String DLL.MedicineFeature.getMedicineName ()
References DLL.MedicineFeature._medicineName.
Referenced by DLL.MedicineFeature.BookToByteArrayBlock(), APP.MainMenu.option3(), APP.MainMenu.option4(), and APP.MainMenu.option5().
getMedicineSupplier()
final String DLL.MedicineFeature.getMedicineSupplier ()
References DLL.MedicineFeature._medicineSupplier.
Referenced by DLL.MedicineFeature.BookToByteArrayBlock(), APP.MainMenu.option3(), and APP.MainMenu.option4().
getPrice()
final double DLL.MedicineFeature.getPrice ()
References DLL.MedicineFeature._price.
Referenced by DLL.MedicineFeature.BookToByteArrayBlock(), APP.MainMenu.option3(), APP.MainMenu.option4(), and APP.MainMenu.option5().
getQuantity()
final int DLL.MedicineFeature.getQuantity ()
References DLL.MedicineFeature._quantity.
Referenced by DLL.MedicineFeature.BookToByteArrayBlock(), APP.MainMenu.option3(), APP.MainMenu.option4(), and APP.MainMenu.option5().
getRack()
final int DLL.MedicineFeature.getRack ()
References DLL.MedicineFeature._rack.
Referenced by DLL.MedicineFeature.BookToByteArrayBlock(), and APP.MainMenu.option3().
setCabnit()
final void DLL.MedicineFeature.setCabnit (int value)
References DLL.MedicineFeature._cabnit.
Referenced by DLL.MainFunctions.AddMedicine(), DLL.MedicineFeature.ByteArrayBlockToBook(), and APP.MainMenu.option3().
setCompanyName()
final void DLL.MedicineFeature.setCompanyName (String value)
References DLL.MedicineFeature._companyName.
Referenced by DLL.MainFunctions.AddMedicine(), DLL.MedicineFeature.ByteArrayBlockToBook(), and APP.MainMenu.option3().
setMedicineId()
final void DLL.MedicineFeature.setMedicineId (int value)
References DLL.MedicineFeature._medicineId.
Referenced by DLL.MainFunctions.AddMedicine(), DLL.MedicineFeature.ByteArrayBlockToBook(), and APP.MainMenu.option3().
setMedicineName()
final void DLL.MedicineFeature.setMedicineName (String value)
References DLL.MedicineFeature._medicineName.
Referenced by DLL.MainFunctions.AddMedicine(), DLL.MedicineFeature.ByteArrayBlockToBook(), and APP.MainMenu.option3().
setMedicineSupplier()
final void DLL.MedicineFeature.setMedicineSupplier (String value)
References DLL.MedicineFeature._medicineSupplier.
Referenced by DLL.MainFunctions.AddMedicine(), DLL.MedicineFeature.ByteArrayBlockToBook(), and APP.MainMenu.option3().
setPrice()
final void DLL.MedicineFeature.setPrice (double value)
References DLL.MedicineFeature._price.
Referenced by DLL.MainFunctions.AddMedicine(), DLL.MedicineFeature.ByteArrayBlockToBook(), and APP.MainMenu.option3().
setQuantity()
final void DLL.MedicineFeature.setQuantity (int value)
References DLL.MedicineFeature._quantity.
Referenced by DLL.MainFunctions.AddMedicine(), DLL.MedicineFeature.ByteArrayBlockToBook(), and APP.MainMenu.option3().
setRack()
final void DLL.MedicineFeature.setRack (int value)
References DLL.MedicineFeature._rack.
Referenced by DLL.MainFunctions.AddMedicine(), DLL.MedicineFeature.ByteArrayBlockToBook(), and APP.MainMenu.option3().
Member Data Documentation
_cabnit
int DLL.MedicineFeature._cabnit private
Referenced by DLL.MedicineFeature.getCabnit(), and DLL.MedicineFeature.setCabnit().
_companyName
String DLL.MedicineFeature._companyName private
Referenced by DLL.MedicineFeature.getCompanyName(), and DLL.MedicineFeature.setCompanyName().
_medicineId
int DLL.MedicineFeature._medicineId private
Referenced by DLL.MedicineFeature.getMedicineId(), and DLL.MedicineFeature.setMedicineId().
_medicineName
String DLL.MedicineFeature._medicineName private
Referenced by DLL.MedicineFeature.getMedicineName(), and DLL.MedicineFeature.setMedicineName().
_medicineSupplier
String DLL.MedicineFeature._medicineSupplier private
Referenced by DLL.MedicineFeature.getMedicineSupplier(), and DLL.MedicineFeature.setMedicineSupplier().
_price
double DLL.MedicineFeature._price private
Referenced by DLL.MedicineFeature.getPrice(), and DLL.MedicineFeature.setPrice().
_quantity
int DLL.MedicineFeature._quantity private
Referenced by DLL.MedicineFeature.getQuantity(), and DLL.MedicineFeature.setQuantity().
_rack
int DLL.MedicineFeature._rack private
Referenced by DLL.MedicineFeature.getRack(), and DLL.MedicineFeature.setRack().
CABNIT_NUMBER_MAX_LENGTH
final int DLL.MedicineFeature.CABNIT_NUMBER_MAX_LENGTH = 4 static
Referenced by DLL.MedicineFeature.BookToByteArrayBlock(), and DLL.MedicineFeature.ByteArrayBlockToBook().
COMPANY_NAME_MAX_LENGTH
final int DLL.MedicineFeature.COMPANY_NAME_MAX_LENGTH = 50 static
Referenced by DLL.MedicineFeature.BookToByteArrayBlock(), and DLL.MedicineFeature.ByteArrayBlockToBook().
MEDICINE_DATA_BLOCK_SIZE
final int DLL.MedicineFeature.MEDICINE_DATA_BLOCK_SIZE = MEDICINE_ID_LENGTH +QUANTITY_MAX_LENGTH + MEDICINE_NAME_MAX_LENGTH + MEDICINE_PRICE_LENGTH + RACK_NUMBER_MAX_LENGTH + CABNIT_NUMBER_MAX_LENGTH + MEDICINE_SUPPLIER_NAME_MAX_LENGTH + COMPANY_NAME_MAX_LENGTH static
Referenced by DLL.MedicineFeature.BookToByteArrayBlock(), DLL.MedicineFeature.ByteArrayBlockToBook(), APP.MainMenu.option3(), APP.MainMenu.option4(), and APP.MainMenu.option5().
MEDICINE_ID_LENGTH
final int DLL.MedicineFeature.MEDICINE_ID_LENGTH = 4 static
Referenced by DLL.MedicineFeature.BookToByteArrayBlock(), and DLL.MedicineFeature.ByteArrayBlockToBook().
MEDICINE_NAME_MAX_LENGTH
final int DLL.MedicineFeature.MEDICINE_NAME_MAX_LENGTH =50 static
Referenced by DLL.MedicineFeature.BookToByteArrayBlock(), and DLL.MedicineFeature.ByteArrayBlockToBook().
MEDICINE_PRICE_LENGTH
final int DLL.MedicineFeature.MEDICINE_PRICE_LENGTH =8 static
Referenced by DLL.MedicineFeature.BookToByteArrayBlock(), and DLL.MedicineFeature.ByteArrayBlockToBook().
MEDICINE_SUPPLIER_NAME_MAX_LENGTH
final int DLL.MedicineFeature.MEDICINE_SUPPLIER_NAME_MAX_LENGTH = 50 static
Referenced by DLL.MedicineFeature.BookToByteArrayBlock(), and DLL.MedicineFeature.ByteArrayBlockToBook().
QUANTITY_MAX_LENGTH
final int DLL.MedicineFeature.QUANTITY_MAX_LENGTH = 4 static
Referenced by DLL.MedicineFeature.BookToByteArrayBlock(), and DLL.MedicineFeature.ByteArrayBlockToBook().
RACK_NUMBER_MAX_LENGTH
final int DLL.MedicineFeature.RACK_NUMBER_MAX_LENGTH = 4 static
Referenced by DLL.MedicineFeature.BookToByteArrayBlock(), and DLL.MedicineFeature.ByteArrayBlockToBook().
The documentation for this class was generated from the following file:
C:/HW/CE-103-2022-2023-HW4-Eray-Burak-Cakir/ce103-hw4-medicalstore-lib/src/DLL/MedicineFeature.java