CE103 Algorithms and Programming I HW4: DLL.BillFeature Class Reference
DLL.BillFeature Class Reference
Public Member Functions
final int getBillId ()
final void setId (int value)
final int getCustomerId ()
final void setCustomerId (int value)
final int getMedicineId ()
final void setMedicineId (int value)
final int getMedicineQuantity ()
final void setMedicineQuantity (int value)
Static Public Member Functions
static byte[] BookToByteArrayBlock (BillFeature bill)
static BillFeature ByteArrayBlockToBook (byte[] byteArray)
Static Public Attributes
static final int BILL_ID_LENGTH = 4
static final int CUSTOMER_ID_MAX_LENGTH = 4
static final int MEDICINE_ID_LENGTH = 4
static final int MEDICINE_QUANTITY_LENGTH = 4
static final int BILL_DATA_BLOCK_SIZE = BILL_ID_LENGTH + CUSTOMER_ID_MAX_LENGTH + MEDICINE_ID_LENGTH + MEDICINE_QUANTITY_LENGTH
Private Attributes
int _billId
int _customerId
int _medicineId
int _medicineQuantity
Member Function Documentation
BookToByteArrayBlock()
static byte[] DLL.BillFeature.BookToByteArrayBlock (BillFeature bill) static
References DLL.BillFeature.BILL_DATA_BLOCK_SIZE, DLL.BillFeature.BILL_ID_LENGTH, DLL.BillFeature.CUSTOMER_ID_MAX_LENGTH, DLL.BillFeature.getBillId(), DLL.BillFeature.getCustomerId(), DLL.BillFeature.getMedicineId(), DLL.BillFeature.getMedicineQuantity(), DLL.DataOperations.integerToByteArray(), DLL.BillFeature.MEDICINE_ID_LENGTH, and DLL.BillFeature.MEDICINE_QUANTITY_LENGTH.
Referenced by DLL.MainFunctions.AddBill().
ByteArrayBlockToBook()
static BillFeature DLL.BillFeature.ByteArrayBlockToBook (byte[] byteArray) static
References DLL.BillFeature.BILL_DATA_BLOCK_SIZE, DLL.BillFeature.BILL_ID_LENGTH, DLL.DataOperations.byteArrayToInteger(), DLL.BillFeature.CUSTOMER_ID_MAX_LENGTH, DLL.BillFeature.getBillId(), DLL.BillFeature.MEDICINE_ID_LENGTH, DLL.BillFeature.MEDICINE_QUANTITY_LENGTH, DLL.BillFeature.setCustomerId(), DLL.BillFeature.setId(), DLL.BillFeature.setMedicineId(), and DLL.BillFeature.setMedicineQuantity().
getBillId()
final int DLL.BillFeature.getBillId ()
References DLL.BillFeature._billId.
Referenced by DLL.BillFeature.BookToByteArrayBlock(), and DLL.BillFeature.ByteArrayBlockToBook().
getCustomerId()
final int DLL.BillFeature.getCustomerId ()
References DLL.BillFeature._customerId.
Referenced by DLL.BillFeature.BookToByteArrayBlock().
getMedicineId()
final int DLL.BillFeature.getMedicineId ()
References DLL.BillFeature._medicineId.
Referenced by DLL.BillFeature.BookToByteArrayBlock().
getMedicineQuantity()
final int DLL.BillFeature.getMedicineQuantity ()
References DLL.BillFeature._medicineQuantity.
Referenced by DLL.BillFeature.BookToByteArrayBlock().
setCustomerId()
final void DLL.BillFeature.setCustomerId (int value)
References DLL.BillFeature._customerId.
Referenced by DLL.MainFunctions.AddBill(), and DLL.BillFeature.ByteArrayBlockToBook().
setId()
final void DLL.BillFeature.setId (int value)
References DLL.BillFeature._billId.
Referenced by DLL.MainFunctions.AddBill(), and DLL.BillFeature.ByteArrayBlockToBook().
setMedicineId()
final void DLL.BillFeature.setMedicineId (int value)
References DLL.BillFeature._medicineId.
Referenced by DLL.MainFunctions.AddBill(), and DLL.BillFeature.ByteArrayBlockToBook().
setMedicineQuantity()
final void DLL.BillFeature.setMedicineQuantity (int value)
References DLL.BillFeature._medicineQuantity.
Referenced by DLL.MainFunctions.AddBill(), and DLL.BillFeature.ByteArrayBlockToBook().
Member Data Documentation
_billId
int DLL.BillFeature._billId private
Referenced by DLL.BillFeature.getBillId(), and DLL.BillFeature.setId().
_customerId
int DLL.BillFeature._customerId private
Referenced by DLL.BillFeature.getCustomerId(), and DLL.BillFeature.setCustomerId().
_medicineId
int DLL.BillFeature._medicineId private
Referenced by DLL.BillFeature.getMedicineId(), and DLL.BillFeature.setMedicineId().
_medicineQuantity
int DLL.BillFeature._medicineQuantity private
Referenced by DLL.BillFeature.getMedicineQuantity(), and DLL.BillFeature.setMedicineQuantity().
BILL_DATA_BLOCK_SIZE
final int DLL.BillFeature.BILL_DATA_BLOCK_SIZE = BILL_ID_LENGTH + CUSTOMER_ID_MAX_LENGTH + MEDICINE_ID_LENGTH + MEDICINE_QUANTITY_LENGTH static
Referenced by DLL.BillFeature.BookToByteArrayBlock(), and DLL.BillFeature.ByteArrayBlockToBook().
BILL_ID_LENGTH
final int DLL.BillFeature.BILL_ID_LENGTH = 4 static
Referenced by DLL.BillFeature.BookToByteArrayBlock(), and DLL.BillFeature.ByteArrayBlockToBook().
CUSTOMER_ID_MAX_LENGTH
final int DLL.BillFeature.CUSTOMER_ID_MAX_LENGTH = 4 static
Referenced by DLL.BillFeature.BookToByteArrayBlock(), and DLL.BillFeature.ByteArrayBlockToBook().
MEDICINE_ID_LENGTH
final int DLL.BillFeature.MEDICINE_ID_LENGTH = 4 static
Referenced by DLL.BillFeature.BookToByteArrayBlock(), and DLL.BillFeature.ByteArrayBlockToBook().
MEDICINE_QUANTITY_LENGTH
final int DLL.BillFeature.MEDICINE_QUANTITY_LENGTH = 4 static
Referenced by DLL.BillFeature.BookToByteArrayBlock(), and DLL.BillFeature.ByteArrayBlockToBook().
The documentation for this class was generated from the following file:
C:/HW/CE-103-2022-2023-HW4-Eray-Burak-Cakir/ce103-hw4-medicalstore-lib/src/DLL/BillFeature.java