CE103 Algorithms and Programming I HW4: APP.MainMenu Class Reference
APP.MainMenu Class Reference
Static Public Member Functions
static void main (String[] args)
Static Private Member Functions
static void option1 ()
static void option2 ()
static void option3 ()
static void option4 ()
static void option5 () throws IOException, InterruptedException
static void option6 ()
Member Function Documentation
main()
static void APP.MainMenu.main (String[] args) static
References APP.MainMenu.option1(), APP.MainMenu.option2(), APP.MainMenu.option3(), APP.MainMenu.option4(), APP.MainMenu.option5(), APP.MainMenu.option6(), and DLL.MenuDesign.printMenu().
option1()
static void APP.MainMenu.option1 () static private
References DLL.MainFunctions.AddSupplier(), DLL.SupplierFeature.BookToByteArrayBlock(), DLL.SupplierFeature.ByteArrayBlockToBook(), DLL.FileOperations.deleteBlock2(), DLL.SupplierFeature.getCityName(), DLL.SupplierFeature.getContactNum(), DLL.SupplierFeature.getEmail(), DLL.SupplierFeature.getId(), DLL.SupplierFeature.getSupplierName(), DLL.FileOperations.readBlock(), DLL.SupplierFeature.setCityName(), DLL.SupplierFeature.setContactNum(), DLL.SupplierFeature.setEmail(), DLL.SupplierFeature.setId(), DLL.SupplierFeature.setSupplierName(), DLL.SupplierFeature.SUPPLIER_DATA_BLOCK_SIZE, and DLL.FileOperations.updateBlock().
Referenced by APP.MainMenu.main(), APP.MainMenu.option3(), and APP.MainMenu.option5().
option2()
static void APP.MainMenu.option2 () static private
References DLL.MainFunctions.AddCustomer(), DLL.CustomerFeature.BookToByteArrayBlock(), DLL.CustomerFeature.ByteArrayBlockToBook(), DLL.CustomerFeature.CUSTOMER_DATA_BLOCK_SIZE, DLL.FileOperations.deleteBlock2(), DLL.CustomerFeature.getCityName(), DLL.CustomerFeature.getContactNum(), DLL.CustomerFeature.getCustomerName(), DLL.CustomerFeature.getEmail(), DLL.CustomerFeature.getId(), DLL.FileOperations.readBlock(), DLL.CustomerFeature.setCityName(), DLL.CustomerFeature.setContactNum(), DLL.CustomerFeature.setCustomerName(), DLL.CustomerFeature.setEmail(), DLL.CustomerFeature.setId(), and DLL.FileOperations.updateBlock().
Referenced by APP.MainMenu.main().
option3()
static void APP.MainMenu.option3 () static private
References DLL.MainFunctions.AddMedicine(), DLL.MainFunctions.AddSaleMedicine(), DLL.MedicineFeature.BookToByteArrayBlock(), DLL.CustomerFeature.ByteArrayBlockToBook(), DLL.MedicineFeature.ByteArrayBlockToBook(), DLL.CustomerFeature.CUSTOMER_DATA_BLOCK_SIZE, DLL.FileOperations.deleteBlock2(), DLL.MedicineFeature.getCabnit(), DLL.CustomerFeature.getCityName(), DLL.MedicineFeature.getCompanyName(), DLL.CustomerFeature.getContactNum(), DLL.CustomerFeature.getCustomerName(), DLL.CustomerFeature.getEmail(), DLL.CustomerFeature.getId(), DLL.MedicineFeature.getMedicineId(), DLL.MedicineFeature.getMedicineName(), DLL.MedicineFeature.getMedicineSupplier(), DLL.MedicineFeature.getPrice(), DLL.MedicineFeature.getQuantity(), DLL.MedicineFeature.getRack(), DLL.MedicineFeature.MEDICINE_DATA_BLOCK_SIZE, APP.MainMenu.option1(), DLL.FileOperations.readBlock(), DLL.MedicineFeature.setCabnit(), DLL.MedicineFeature.setCompanyName(), DLL.MedicineFeature.setMedicineId(), DLL.MedicineFeature.setMedicineName(), DLL.MedicineFeature.setMedicineSupplier(), DLL.MedicineFeature.setPrice(), DLL.MedicineFeature.setQuantity(), DLL.MedicineFeature.setRack(), and DLL.FileOperations.updateBlock().
Referenced by APP.MainMenu.main().
option4()
static void APP.MainMenu.option4 () static private
References DLL.MedicineFeature.ByteArrayBlockToBook(), DLL.SaleMedicineFeature.ByteArrayBlockToBook(), DLL.MedicineFeature.getCompanyName(), DLL.SaleMedicineFeature.getCustomerId(), DLL.MedicineFeature.getMedicineId(), DLL.SaleMedicineFeature.getMedicineId(), DLL.MedicineFeature.getMedicineName(), DLL.SaleMedicineFeature.getMedicineQuantity(), DLL.MedicineFeature.getMedicineSupplier(), DLL.MedicineFeature.getPrice(), DLL.MedicineFeature.getQuantity(), DLL.MedicineFeature.MEDICINE_DATA_BLOCK_SIZE, DLL.FileOperations.readBlock(), and DLL.SaleMedicineFeature.SALE_DATA_BLOCK_SIZE.
Referenced by APP.MainMenu.main().
option5()
static void APP.MainMenu.option5 () throws IOException, InterruptedException static private
References DLL.MainFunctions.AddBill(), DLL.CustomerFeature.ByteArrayBlockToBook(), DLL.MedicineFeature.ByteArrayBlockToBook(), DLL.CustomerFeature.CUSTOMER_DATA_BLOCK_SIZE, DLL.CustomerFeature.getCityName(), DLL.MedicineFeature.getCompanyName(), DLL.CustomerFeature.getContactNum(), DLL.CustomerFeature.getCustomerName(), DLL.CustomerFeature.getEmail(), DLL.CustomerFeature.getId(), DLL.MedicineFeature.getMedicineId(), DLL.MedicineFeature.getMedicineName(), DLL.MedicineFeature.getPrice(), DLL.MedicineFeature.getQuantity(), DLL.MedicineFeature.MEDICINE_DATA_BLOCK_SIZE, APP.MainMenu.option1(), and DLL.FileOperations.readBlock().
Referenced by APP.MainMenu.main().
option6()
static void APP.MainMenu.option6 () static private
Referenced by APP.MainMenu.main().
The documentation for this class was generated from the following file:
C:/HW/CE-103-2022-2023-HW4-Eray-Burak-Cakir/ce103-hw4-medicalstore-app/src/APP/MainMenu.java