CE103 Algorithms and Programming I HW4: DLL.SaleMedicineFeature Class Reference
DLL.SaleMedicineFeature Class Reference
Public Member Functions
final int getCustomerId ()
final void setCustomerId (int value)
final int getMedicineId ()
final void setMedicineId (int value)
final int getMedicineQuantity ()
final void setMedicineQuantity (int value)
final String getSaleDate ()
final void setSaleDate (String value)
Static Public Member Functions
static byte[] BookToByteArrayBlock (SaleMedicineFeature sale)
static SaleMedicineFeature ByteArrayBlockToBook (byte[] byteArray)
Static Public Attributes
static final int CUSTOMER_ID_MAX_LENGTH = 4
static final int MEDICINE_ID_LENGTH = 4
static final int MEDICINE_QUANTITY_LENGTH = 4
static final int SALE_DATE =4
static final int SALE_DATA_BLOCK_SIZE = SALE_DATE+CUSTOMER_ID_MAX_LENGTH + MEDICINE_ID_LENGTH + MEDICINE_QUANTITY_LENGTH
Private Attributes
int _customerId
int _medicineId
int _medicineQuantity
String _saleDate
Member Function Documentation
BookToByteArrayBlock()
static byte[] DLL.SaleMedicineFeature.BookToByteArrayBlock (SaleMedicineFeature sale) static
References DLL.SaleMedicineFeature.CUSTOMER_ID_MAX_LENGTH, DLL.SaleMedicineFeature.getCustomerId(), DLL.SaleMedicineFeature.getMedicineId(), DLL.SaleMedicineFeature.getMedicineQuantity(), DLL.SaleMedicineFeature.getSaleDate(), DLL.DataOperations.integerToByteArray(), DLL.SaleMedicineFeature.MEDICINE_ID_LENGTH, DLL.SaleMedicineFeature.MEDICINE_QUANTITY_LENGTH, DLL.SaleMedicineFeature.SALE_DATA_BLOCK_SIZE, DLL.SaleMedicineFeature.SALE_DATE, and DLL.DataOperations.StringToByteArray().
Referenced by DLL.MainFunctions.AddSaleMedicine().
ByteArrayBlockToBook()
static SaleMedicineFeature DLL.SaleMedicineFeature.ByteArrayBlockToBook (byte[] byteArray) static
References DLL.DataOperations.byteArrayToInteger(), DLL.DataOperations.byteArrayToString(), DLL.SaleMedicineFeature.CUSTOMER_ID_MAX_LENGTH, DLL.SaleMedicineFeature.getMedicineId(), DLL.SaleMedicineFeature.MEDICINE_ID_LENGTH, DLL.SaleMedicineFeature.MEDICINE_QUANTITY_LENGTH, DLL.SaleMedicineFeature.SALE_DATA_BLOCK_SIZE, DLL.SaleMedicineFeature.SALE_DATE, DLL.SaleMedicineFeature.setCustomerId(), DLL.SaleMedicineFeature.setMedicineId(), DLL.SaleMedicineFeature.setMedicineQuantity(), and DLL.SaleMedicineFeature.setSaleDate().
Referenced by APP.MainMenu.option4().
getCustomerId()
final int DLL.SaleMedicineFeature.getCustomerId ()
References DLL.SaleMedicineFeature._customerId.
Referenced by DLL.SaleMedicineFeature.BookToByteArrayBlock(), and APP.MainMenu.option4().
getMedicineId()
final int DLL.SaleMedicineFeature.getMedicineId ()
References DLL.SaleMedicineFeature._medicineId.
Referenced by DLL.SaleMedicineFeature.BookToByteArrayBlock(), DLL.SaleMedicineFeature.ByteArrayBlockToBook(), and APP.MainMenu.option4().
getMedicineQuantity()
final int DLL.SaleMedicineFeature.getMedicineQuantity ()
References DLL.SaleMedicineFeature._medicineQuantity.
Referenced by DLL.SaleMedicineFeature.BookToByteArrayBlock(), and APP.MainMenu.option4().
getSaleDate()
final String DLL.SaleMedicineFeature.getSaleDate ()
References DLL.SaleMedicineFeature._saleDate.
Referenced by DLL.SaleMedicineFeature.BookToByteArrayBlock().
setCustomerId()
final void DLL.SaleMedicineFeature.setCustomerId (int value)
References DLL.SaleMedicineFeature._customerId.
Referenced by DLL.MainFunctions.AddSaleMedicine(), and DLL.SaleMedicineFeature.ByteArrayBlockToBook().
setMedicineId()
final void DLL.SaleMedicineFeature.setMedicineId (int value)
References DLL.SaleMedicineFeature._medicineId.
Referenced by DLL.MainFunctions.AddSaleMedicine(), and DLL.SaleMedicineFeature.ByteArrayBlockToBook().
setMedicineQuantity()
final void DLL.SaleMedicineFeature.setMedicineQuantity (int value)
References DLL.SaleMedicineFeature._medicineQuantity.
Referenced by DLL.MainFunctions.AddSaleMedicine(), and DLL.SaleMedicineFeature.ByteArrayBlockToBook().
setSaleDate()
final void DLL.SaleMedicineFeature.setSaleDate (String value)
References DLL.SaleMedicineFeature._saleDate.
Referenced by DLL.MainFunctions.AddSaleMedicine(), and DLL.SaleMedicineFeature.ByteArrayBlockToBook().
Member Data Documentation
_customerId
int DLL.SaleMedicineFeature._customerId private
Referenced by DLL.SaleMedicineFeature.getCustomerId(), and DLL.SaleMedicineFeature.setCustomerId().
_medicineId
int DLL.SaleMedicineFeature._medicineId private
Referenced by DLL.SaleMedicineFeature.getMedicineId(), and DLL.SaleMedicineFeature.setMedicineId().
_medicineQuantity
int DLL.SaleMedicineFeature._medicineQuantity private
Referenced by DLL.SaleMedicineFeature.getMedicineQuantity(), and DLL.SaleMedicineFeature.setMedicineQuantity().
_saleDate
String DLL.SaleMedicineFeature._saleDate private
Referenced by DLL.SaleMedicineFeature.getSaleDate(), and DLL.SaleMedicineFeature.setSaleDate().
CUSTOMER_ID_MAX_LENGTH
final int DLL.SaleMedicineFeature.CUSTOMER_ID_MAX_LENGTH = 4 static
Referenced by DLL.SaleMedicineFeature.BookToByteArrayBlock(), and DLL.SaleMedicineFeature.ByteArrayBlockToBook().
MEDICINE_ID_LENGTH
final int DLL.SaleMedicineFeature.MEDICINE_ID_LENGTH = 4 static
Referenced by DLL.SaleMedicineFeature.BookToByteArrayBlock(), and DLL.SaleMedicineFeature.ByteArrayBlockToBook().
MEDICINE_QUANTITY_LENGTH
final int DLL.SaleMedicineFeature.MEDICINE_QUANTITY_LENGTH = 4 static
Referenced by DLL.SaleMedicineFeature.BookToByteArrayBlock(), and DLL.SaleMedicineFeature.ByteArrayBlockToBook().
SALE_DATA_BLOCK_SIZE
final int DLL.SaleMedicineFeature.SALE_DATA_BLOCK_SIZE = SALE_DATE+CUSTOMER_ID_MAX_LENGTH + MEDICINE_ID_LENGTH + MEDICINE_QUANTITY_LENGTH static
Referenced by DLL.SaleMedicineFeature.BookToByteArrayBlock(), DLL.SaleMedicineFeature.ByteArrayBlockToBook(), and APP.MainMenu.option4().
SALE_DATE
final int DLL.SaleMedicineFeature.SALE_DATE =4 static
Referenced by DLL.SaleMedicineFeature.BookToByteArrayBlock(), and DLL.SaleMedicineFeature.ByteArrayBlockToBook().
The documentation for this class was generated from the following file:
C:/HW/CE-103-2022-2023-HW4-Eray-Burak-Cakir/ce103-hw4-medicalstore-lib/src/DLL/SaleMedicineFeature.java