CE103 Algorithms and Programming I HW4: DLL.DataOperations Class Reference
DLL.DataOperations Class Reference
Static Public Member Functions
static int[] ToByte (String hexString)
static String ToHex (byte[] arr)
static boolean IsHex (String str)
static int GetInt (byte[] data, int offset, int length)
static String ToAscii (String hexString)
static long byteArrayToLong (byte[] byteArray)
static int byteArrayToInteger (byte[] byteArray)
static byte[] integerToByteArray (int value)
static byte[] convertLongToByteArray (long value)
static byte[] floatToByteArray (float value)
static float byteArrayToFloat (byte[] byteArray)
static byte[] StringToByteArray (String data)
static double byteArrayToDouble (byte[] byteArray)
static byte[] doubleToByteArray (double value)
static String byteArrayToString (byte[] byteArray)
Member Function Documentation
byteArrayToDouble()
static double DLL.DataOperations.byteArrayToDouble (byte[] byteArray) static
Referenced by DLL.MedicineFeature.ByteArrayBlockToBook().
byteArrayToFloat()
static float DLL.DataOperations.byteArrayToFloat (byte[] byteArray) static
Referenced by DLL.UnitTest.testByteArrayToFloat().
byteArrayToInteger()
static int DLL.DataOperations.byteArrayToInteger (byte[] byteArray) static
Referenced by DLL.BillFeature.ByteArrayBlockToBook(), DLL.CustomerFeature.ByteArrayBlockToBook(), DLL.MedicineFeature.ByteArrayBlockToBook(), DLL.SaleMedicineFeature.ByteArrayBlockToBook(), DLL.SupplierFeature.ByteArrayBlockToBook(), and DLL.UnitTest.testByteArrayToInteger().
byteArrayToLong()
static long DLL.DataOperations.byteArrayToLong (byte[] byteArray) static
Referenced by DLL.CustomerFeature.ByteArrayBlockToBook(), DLL.SupplierFeature.ByteArrayBlockToBook(), and DLL.UnitTest.testByteArrayToLong().
byteArrayToString()
static String DLL.DataOperations.byteArrayToString (byte[] byteArray) static
Referenced by DLL.CustomerFeature.ByteArrayBlockToBook(), DLL.MedicineFeature.ByteArrayBlockToBook(), DLL.SaleMedicineFeature.ByteArrayBlockToBook(), DLL.SupplierFeature.ByteArrayBlockToBook(), and DLL.UnitTest.testByteArrayToString().
convertLongToByteArray()
static byte[] DLL.DataOperations.convertLongToByteArray (long value) static
Referenced by DLL.CustomerFeature.BookToByteArrayBlock(), and DLL.SupplierFeature.BookToByteArrayBlock().
doubleToByteArray()
static byte[] DLL.DataOperations.doubleToByteArray (double value) static
Referenced by DLL.MedicineFeature.BookToByteArrayBlock().
floatToByteArray()
static byte[] DLL.DataOperations.floatToByteArray (float value) static
GetInt()
static int DLL.DataOperations.GetInt (byte[] data, int offset, int length) static
Referenced by DLL.UnitTest.testGetInt().
integerToByteArray()
static byte[] DLL.DataOperations.integerToByteArray (int value) static
Referenced by DLL.BillFeature.BookToByteArrayBlock(), DLL.CustomerFeature.BookToByteArrayBlock(), DLL.MedicineFeature.BookToByteArrayBlock(), DLL.SaleMedicineFeature.BookToByteArrayBlock(), and DLL.SupplierFeature.BookToByteArrayBlock().
IsHex()
static boolean DLL.DataOperations.IsHex (String str) static
References DLL.DataOperations.ToByte().
Referenced by DLL.UnitTest.testIsHex().
StringToByteArray()
static byte[] DLL.DataOperations.StringToByteArray (String data) static
Referenced by DLL.CustomerFeature.BookToByteArrayBlock(), DLL.MedicineFeature.BookToByteArrayBlock(), DLL.SaleMedicineFeature.BookToByteArrayBlock(), DLL.SupplierFeature.BookToByteArrayBlock(), and DLL.FileOperations.deleteBlock2().
ToAscii()
static String DLL.DataOperations.ToAscii (String hexString) static
ToByte()
static int[] DLL.DataOperations.ToByte (String hexString) static
Referenced by DLL.DataOperations.IsHex(), and DLL.UnitTest.testHexStringToByteArray().
ToHex()
static String DLL.DataOperations.ToHex (byte[] arr) static
The documentation for this class was generated from the following file:
C:/HW/CE-103-2022-2023-HW4-Eray-Burak-Cakir/ce103-hw4-medicalstore-lib/src/DLL/DataOperations.java